"use client";
import React from 'react';
import { BrainCircuit, Sparkles, Activity } from 'lucide-react';
import { useEVData } from '@/context/EVDataContext';

export default function AIInsightsPage() {
  const { vehicleData, insights } = useEVData();

  if (!vehicleData.isConnected) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[60vh] space-y-4 text-center">
        <div className="p-10 bg-white border border-slate-100 rounded-3xl shadow-sm">
          <BrainCircuit className="w-12 h-12 text-slate-200 mx-auto mb-4 animate-pulse" />
          <h3 className="text-xl font-bold text-slate-900 font-outfit">AI Intelligence Offline</h3>
          <p className="text-slate-500 text-xs mt-1">Llama 3.1 analysis requires an active telemetry stream.</p>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-8">
      <div>
        <h2 className="text-2xl font-bold tracking-tight text-slate-900 font-outfit">AI Cognitive Center</h2>
        <p className="text-slate-500 text-xs mt-1">Autonomous observations and predictive intelligence reports generated by Groq.</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
        <div className="lg:col-span-1 space-y-4">
          <div className="bg-slate-900 text-white rounded-2xl p-6 shadow-xl relative overflow-hidden">
             <div className="absolute top-0 right-0 w-16 h-16 bg-blue-600/20 blur-3xl" />
            <BrainCircuit className="w-8 h-8 mb-4 text-blue-400" />
            <h3 className="text-lg font-bold font-outfit">Groq AI Active</h3>
            <p className="text-slate-400 text-[10px] uppercase tracking-widest font-bold mt-1">Llama 3.1 70B Versatile</p>
          </div>
          
          <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-sm">
            <h4 className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-4">Real-time Metrics</h4>
            <div className="space-y-4">
              <FocusItem label="Est. Range" value={`${insights?.predicted_range || 0} km`} />
              <FocusItem label="Health Score" value={`${insights?.health_score || 0}%`} />
              <FocusItem label="Thermal State" value={insights?.risk_level || "Checking..."} />
              <FocusItem label="Behavior" value={insights?.behavior || "Analyzing..."} />
            </div>
          </div>
        </div>

        <div className="lg:col-span-3 space-y-6">
          <div className="bg-white border border-slate-200 rounded-xl p-8 shadow-sm">
            <div className="flex items-center gap-3 mb-6">
              <Sparkles className="w-5 h-5 text-blue-600" />
              <h3 className="font-bold text-lg font-outfit">Primary AI Diagnostic Report</h3>
            </div>
            <p className="text-base text-slate-700 leading-relaxed italic border-l-4 border-blue-500 pl-6 py-2 bg-slate-50 rounded-r-xl">
              "{insights?.ai_diagnostic || "Processing raw sensor arrays for comprehensive diagnostic sweep..."}"
            </p>
          </div>

          <div className="bg-blue-600 text-white rounded-2xl p-8 shadow-lg shadow-blue-100">
            <h3 className="font-bold text-lg mb-4 flex items-center gap-2 font-outfit">
              <Activity className="w-5 h-5" />
              AI Driver Coaching Protocol
            </h3>
            <p className="text-blue-50 text-sm leading-relaxed font-medium">
              {insights?.coach_advice || "Analyzing telemetry for personalized efficiency optimization..."}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

function FocusItem({ label, value }) {
  return (
    <div className="flex justify-between items-center py-2 border-b border-slate-50 last:border-0">
      <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">{label}</span>
      <span className="text-xs font-bold text-slate-900">{value}</span>
    </div>
  );
}
